[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

[lib]
name = "rusty"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.4", features = ["extension-module"] }
rust-fuzzy-search = "0.1.1"
